version: '3'
services:
  grok3-proxy:
    image: ghcr.io/songdaopi/grok3_api:latest
    ports:
      - "8180:8180"
    environment:
      - GROK3_AUTH_TOKEN=your_token_here
      - GROK3_COOKIE=your_cookie_here
