version: '3.8'
services:
  grok3-proxy:
    image: ghcr.io/supmamamamma/grok3_api:latest
    container_name: grok3-proxy
    ports:
      - "8180:8180"  # 默认端口8180，可通过环境变量修改
    environment:
      # 必需的配置
      - GROK3_AUTH_TOKEN=${GROK3_AUTH_TOKEN:-your_token_here}  # 认证令牌
      - GROK3_COOKIE=${GROK3_COOKIE:-your_cookie_here}         # Grok cookie

      # 可选的配置
      - TEXT_BEFORE_PROMPT=${TEXT_BEFORE_PROMPT:-}  # 提示词前的文本
      - TEXT_AFTER_PROMPT=${TEXT_AFTER_PROMPT:-}    # 提示词后的文本
      - KEEP_CHAT=${KEEP_CHAT:-false}              # 是否保持聊天会话
      - IGNORE_THINKING=${IGNORE_THINKING:-false}   # 是否忽略思考内容
      - HTTP_PROXY=${HTTP_PROXY:-}                  # HTTP/SOCKS5 代理设置
      - TZ=${TZ:-Asia/Shanghai}                    # 时区设置

    command: [
      "./grok3-openai-proxy",
      "-port", "8180",
      # 根据环境变量动态添加参数
      "${TEXT_BEFORE_PROMPT:+-textBeforePrompt}", "${TEXT_BEFORE_PROMPT:-}",
      "${TEXT_AFTER_PROMPT:+-textAfterPrompt}", "${TEXT_AFTER_PROMPT:-}",
      "${KEEP_CHAT:+-keepChat=true}",
      "${IGNORE_THINKING:+-ignoreThinking=true}",
      "${HTTP_PROXY:+-httpProxy}", "${HTTP_PROXY:-}"
    ]
    
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8180/v1/models"]
      interval: 30s
      timeout: 3s
      retries: 3
    
    restart: unless-stopped
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
